version: "3"
services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=better-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"
