services:
  app:
    container_name: better-app
    image: better-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "postgresql://postgres:mysecretpassword@db:5432/better-db"
    ports:
      - "5173:5173"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@db:5432/better-db"
    command: >
      sh -c "npm install && npm run generate && npm run migrate && node build/index.js"

  db:
    container_name: better-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: better-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
